import Head from "next/head"
import Sidebar from "./Sidebar"
import Rightbar from "./Rightbar"
import styles from '../styles/Layout.module.css'

export default function Layout({children}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>에잇</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <Sidebar/>
      {children}
      <Rightbar/>
    </div>
  )
}
