import Head from "next/head"
import Sidebar from "./Sidebar"
import Rightbar from "./Rightbar"
import styles from '../styles/Layout.module.css'

/*
==================================================
===============화면 레이아웃 컴포넌트==================
==================================================
수정일자 : 2022. 06. 21
사용 페이지 : /_app.js
완 : UI 구현
미완: 
*/

export default function Layout({children}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>에잇</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <Sidebar/>
      {children}
      <Rightbar/>      
    </div>
  )
}
